### ISSUE TITLE
"Your Data" not showing first member in array elements

### ISSUE THREAD

**Issue by WFDexter** [SOM-Research/jsonDiscoverer#12]
The "Your Data" output is treating the first member value in an element of an array as the value of that array element.

It's entirely possible that this is intentional and I just don't fully understand what it's supposed to be doing, but it seems odd.

Example:

    [
        {
            "Value": [
                {
                    "SchoolDay": "false",
                    "ScheduleDate": "20150921",
                    "CloseDay": "0"
                }
            ]
        }
    ]

Results in the attached. I expected something more like

    +-------------------------+
    | Value                   |
    +-------------------------+
    | SchoolDay : false       |
    | ScheduleDate : 20150921 |
    | CloseDay : 0            |
    +-------------------------+

![untitled](https://cloud.githubusercontent.com/assets/10853315/10052668/b3cd679a-61ed-11e5-8b28-6901722fc04b.png)

**Comment by jlcanovas** [comment]
Hi, 

if I'm not wrong, this is the normal behaviour for the library we use to render the diagram. It needs something to name the class and if it does not find any "name"/"id" attribute, it will take the first one. 

Let me check to see if I can tune this.

Thanks for reporting this!

**Comment by jlcanovas** [comment]
Hi,

I've been working on this. It turned out that the library we are using to render the diagram took the first attribute of the class as its name. The new implementation simply does not use any attribute to render the name of the class and therefore all its attributes are included below.

See the new result for your JSON:

![captura](https://cloud.githubusercontent.com/assets/1996760/10131687/50d6fb4a-65d2-11e5-839b-db4dfcfbbd2c.PNG)
